// Generated by CoffeeScript 1.6.3
(function() {
  var TIMER, animateRandomOpacity, animateRandomShuffles, bindSpotlight, getWindowCoords, minMax, removeShuffles;

  TIMER = null;

  minMax = function(i, boundary) {
    if (i > boundary) {
      i = boundary;
    }
    if (i < -boundary) {
      i = -boundary;
    }
    return i;
  };

  getWindowCoords = function() {
    var left, rect, top;
    rect = $(".logo")[0].getBoundingClientRect();
    left = rect.left;
    top = rect.top;
    return [left + 468, top + 144];
  };

  bindSpotlight = function() {
    var body_height, body_width, border_left_width, border_right_width, left_adjust, orig_top;
    body_width = $(document).width();
    body_height = $(document).height();
    $(".spotlight").css({
      "border-bottom-width": "" + (body_width / 2 + 350) + "px"
    });
    left_adjust = parseInt($(".spotlight").css("left").replace("px", ""));
    border_left_width = parseInt($(".spotlight").css("border-left-width").replace("px", ""));
    border_right_width = parseInt($(".spotlight").css("border-right-width").replace("px", ""));
    orig_top = parseInt($(".spotlight").css("top").replace("px", ""));
    return $(document).mousemove(function(e) {
      var currentLeft, currentTop, excess_offset, left, max_offset, new_left_adjust, new_left_width, new_right_width, origin_css_attr, r, rotate_css_attr, top, total_rotation, x_offset, y_offset, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _results, _results1;
      _ref = getWindowCoords(), left = _ref[0], top = _ref[1];
      rotate_css_attr = ["transform", "-ms-transform", "-webkit-transform"];
      origin_css_attr = ["transform-origin", "-ms-transform-origin", "-webkit-transform-origin"];
      currentLeft = e.pageX;
      currentTop = e.pageY;
      x_offset = currentLeft - left;
      y_offset = currentTop - top;
      max_offset = 250;
      excess_offset = 0;
      if (y_offset < 0) {
        $(".spotlight").addClass("hidden");
        return;
      }
      $(".spotlight").removeClass("hidden");
      if (x_offset > max_offset) {
        excess_offset = x_offset - max_offset;
        x_offset = max_offset;
      }
      if (x_offset < -max_offset) {
        excess_offset = x_offset + max_offset;
        x_offset = -max_offset;
      }
      excess_offset = minMax(excess_offset, 170);
      if (excess_offset === 0) {
        $(".spotlight").css("left", "" + left_adjust + "px");
        $(".spotlight").css("border-right-width", "" + border_right_width + "px");
        $(".spotlight").css("border-left-width", "" + border_left_width + "px");
        for (_i = 0, _len = rotate_css_attr.length; _i < _len; _i++) {
          r = rotate_css_attr[_i];
          $(".spotlight").css(r, "rotate(0deg)");
        }
        new_right_width = border_right_width + x_offset;
        new_left_width = border_left_width - x_offset;
        new_left_adjust = left_adjust + x_offset;
        $(".spotlight").css("border-right-width", "" + new_right_width + "px");
        $(".spotlight").css("border-left-width", "" + new_left_width + "px");
        return $(".spotlight").css("left", "" + new_left_adjust + "px");
      } else if (excess_offset < 0) {
        new_left_adjust = left_adjust - max_offset;
        $(".spotlight").css("left", "" + new_left_adjust + "px");
        $(".spotlight").css("border-right-width", "0px");
        $(".spotlight").css("border-left-width", "" + (border_left_width + max_offset) + "px");
        excess_offset = excess_offset / 10;
        for (_j = 0, _len1 = origin_css_attr.length; _j < _len1; _j++) {
          r = origin_css_attr[_j];
          $(".spotlight").css(r, "100% 0%");
        }
        _results = [];
        for (_k = 0, _len2 = rotate_css_attr.length; _k < _len2; _k++) {
          r = rotate_css_attr[_k];
          total_rotation = -excess_offset;
          total_rotation = minMax(total_rotation, 30);
          _results.push($(".spotlight").css(r, "rotate(" + (total_rotation * 3) + "deg)"));
        }
        return _results;
      } else {
        new_left_adjust = left_adjust + max_offset;
        $(".spotlight").css("left", "" + new_left_adjust + "px");
        $(".spotlight").css("border-right-width", "" + (border_left_width + max_offset) + "px");
        $(".spotlight").css("border-left-width", "0px");
        excess_offset = excess_offset * 8;
        excess_offset = Math.pow(excess_offset, 0.68);
        for (_l = 0, _len3 = origin_css_attr.length; _l < _len3; _l++) {
          r = origin_css_attr[_l];
          $(".spotlight").css(r, "0% 0%");
        }
        _results1 = [];
        for (_m = 0, _len4 = rotate_css_attr.length; _m < _len4; _m++) {
          r = rotate_css_attr[_m];
          total_rotation = -excess_offset / 3;
          total_rotation = minMax(total_rotation, 55);
          _results1.push($(".spotlight").css(r, "rotate(" + total_rotation + "deg)"));
        }
        return _results1;
      }
    });
  };

  animateRandomOpacity = function() {
    var images, non_bright_images, selected_img;
    images = $(".random-opacity-animation").find(".custom3");
    non_bright_images = _.filter(images, function(img) {
      return !$(img).hasClass("bright");
    });
    $(".bright").removeClass("bright");
    selected_img = non_bright_images[Math.floor(Math.random() * non_bright_images.length)];
    return $(selected_img).addClass("bright");
  };

  animateRandomShuffles = function() {
    var images, non_bright_images, selected_img;
    images = $(".random-opacity-animation").find(".img-border");
    non_bright_images = _.filter(images, function(img) {
      return !$(img).hasClass("shuffled");
    });
    selected_img = non_bright_images[Math.floor(Math.random() * non_bright_images.length)];
    return $(selected_img).addClass("shuffled");
  };

  removeShuffles = function() {
    return $(".shuffled").removeClass("shuffled");
  };

  $(document).ready(function() {
    var animations;
    if ($(".spotlight").length > 0) {
      bindSpotlight();
    }
    $(".nav-widget").mouseover(function() {
      return console.log("over");
    });
    animations = [animateRandomOpacity, animateRandomShuffles, removeShuffles];
    setInterval((function() {
      return animations[Math.floor(Math.random() * animations.length)]();
    }), 1000);
    $(".custom3").on("mouseover", function(evt) {
      return $(evt.target).find(".img-overlay").removeClass("hidden");
    });
    $(".img-overlay").on("mouseout", function(evt) {
      return $(".img-overlay").addClass("hidden");
    });
    if ($('body').width() < 992) {
      $(".top-widget").css("opacity", "1");
      $(".top-widget").css("font-size", "0.7em");
      $(".top-widget p").css("border-bottom", "0");
      $(".spotlight").css("opacity", "0");
      $(".nav-widget").css("opacity", "1");
      $(".nav-widget").css("height", "auto");
      $(".brand-info").css("position", "static");
      return $(".brand-info").css("padding-bottom", "10px");
    }
  });

}).call(this);
